name: KLIMEŠNÍČEK Backend
version: "1.0.0"
slug: klimesnicek
description: Jednoduchý jídelní backend s FastAPI a SQLite
startup: services
boot: auto
hassio_api: false
homeassistant_api: false
host_network: true
options: {}
schema: {}
